name: share_plus
description: Flutter plugin for sharing content via the platform share UI, using the ACTION_SEND intent on Android and UIActivityViewController on iOS.
version: 3.0.4
homepage: https://plus.fluttercommunity.dev/
repository: https://github.com/fluttercommunity/plus_plugins/tree/main/packages/

flutter:
  plugin:
    platforms:
      android:
        package: dev.fluttercommunity.plus.share
        pluginClass: SharePlusPlugin
      ios:
        pluginClass: FLTSharePlusPlugin
      linux:
        default_package: share_plus_linux
      macos:
        default_package: share_plus_macos
      web:
        default_package: share_plus_web
      windows:
        default_package: share_plus_windows

dependencies:
  meta: ^1.7.0
  mime: ^1.0.0
  flutter:
    sdk: flutter
  share_plus_platform_interface:
    git:
      url: https://github.com/sarbagyastha/plus_plugins.git
      path: packages/share_plus/share_plus_platform_interface
  share_plus_linux:
    git:
      url: https://github.com/sarbagyastha/plus_plugins.git
      path: packages/share_plus/share_plus_linux
  share_plus_macos:
    git:
      url: https://github.com/sarbagyastha/plus_plugins.git
      path: packages/share_plus/share_plus_macos
  share_plus_windows:
    git:
      url: https://github.com/sarbagyastha/plus_plugins.git
      path: packages/share_plus/share_plus_windows
  share_plus_web:
    git:
      url: https://github.com/sarbagyastha/plus_plugins.git
      path: packages/share_plus/share_plus_web


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.12.13+hotfix.5"
