name: regular_integration_tests
publish_to: none

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  share_plus_web:
    git:
      url: https://github.com/sarbagyastha/plus_plugins.git
      path: packages/share_plus/share_plus_web
  http: ^0.12.2
  mockito: ^5.0.0

dependency_overrides:
  args: ^2.0.0
  convert: ^3.0.0
  crypto: ^3.0.0
